version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - timescaledb
      - redis
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - strategy-network
      
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=funding_strategy
    volumes:
      - timescale-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strategy-network
  
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - strategy-network
  
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - strategy-network
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - strategy-network

volumes:
  timescale-data:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  strategy-network:
    driver: bridge
